sails:
  build: .
  volumes:
    - .:/app
  ports:
    - "1337:1337"
  links:
    - postgres
    
postgres:
  image: postgres:9.3
  ports:
    - "5432:5432"
  volumes_from:
    - bds_data
  command: postgres -d 2